version: '3.8'

services:
  visualization:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - API_BASE_URL=http://backend:8080
      - SECRET_KEY=change-this-in-production
    volumes:
      - ./app:/app/app
    depends_on:
      - backend
    networks:
      - areum-network

  backend:
    image: areum-backend:latest
    ports:
      - "8080:8080"
    environment:
      - APP_ENVIRONMENT=production
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/areum_db
    depends_on:
      - postgres
    networks:
      - areum-network

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: areum_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - areum-network

volumes:
  postgres-data:

networks:
  areum-network:
    driver: bridge